version: '3.7'
services:
  database:
    image: mysql:5.7
    container_name: mysql_flask_example
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - './mysql-data/db:/var/lib/mysql'
  backend:
    restart: always
    container_name: flask_example
    image: lifangjunone/flask_example:v1.0.4
    command: /bin/bash -c /usr/src/backend/deploy/start_server.sh
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - /tmp/flask_example/:/usr/scr/backend/
    environment:
      - TZ=Asia/Shanghai
      - ENVIRONMENT=${ENVIRONMENT}
      - CURRENT_VERSION=${CURRENT_VERSION}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}

